# Generated by Django 3.2.6 on 2021-08-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('author', models.CharField(max_length=50)),
                ('datecreated', models.DateTimeField(auto_now=True)),
                ('Inventory', models.IntegerField()),
                ('price', models.PositiveBigIntegerField()),
            ],
        ),
    ]
