# Generated by Django 3.2.6 on 2021-08-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210819_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='title',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
