# Generated by Django 3.2.6 on 2021-08-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_description_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='name',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
