# Generated by Django 3.2.6 on 2021-08-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='name_book',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
